export const userAllUSer = (req, res) => {
    const allUserDataDB = [
        {
            id: 1,
            name: "Rahul Sharma",
            email: "rahul.sharma@example.com",
            phone: "9876543210",
            role: "Student",
            city: "Delhi",
        },
        {
            id: 2,
            name: "Priya Verma",
            email: "priya.verma@example.com",
            phone: "9876543211",
            role: "Student",
            city: "Mumbai",
        },
        {
            id: 3,
            name: "Amit Kumar",
            email: "amit.kumar@example.com",
            phone: "9876543212",
            role: "Instructor",
            city: "Lucknow",
        },
        {
            id: 4,
            name: "Sneha Gupta",
            email: "sneha.gupta@example.com",
            phone: "9876543213",
            role: "Student",
            city: "Jaipur",
        },
        {
            id: 5,
            name: "Rohit Singh",
            email: "rohit.singh@example.com",
            phone: "9876543214",
            role: "Admin",
            city: "Chandigarh",
        },
        {
            id: 6,
            name: "Neha Kapoor",
            email: "neha.kapoor@example.com",
            phone: "9876543215",
            role: "Student",
            city: "Pune",
        },
        {
            id: 7,
            name: "Vikas Yadav",
            email: "vikas.yadav@example.com",
            phone: "9876543216",
            role: "Student",
            city: "Kanpur",
        },
        {
            id: 8,
            name: "Anjali Mehta",
            email: "anjali.mehta@example.com",
            phone: "9876543217",
            role: "Instructor",
            city: "Ahmedabad",
        },
        {
            id: 9,
            name: "Karan Malhotra",
            email: "karan.malhotra@example.com",
            phone: "9876543218",
            role: "Student",
            city: "Bhopal",
        },
        {
            id: 10,
            name: "Pooja Arora",
            email: "pooja.arora@example.com",
            phone: "9876543219",
            role: "Student",
            city: "Noida",
        },
    ];

    res.send({ message: 'Sucessfully send USer Data', data: allUserDataDB })
}

export const order = (req, res) => {
    const allorderdataDB = [
        {
            id: 1,
            orderId: "ORD1001",
            customerName: "Rahul Sharma",
            product: "Laptop",
            quantity: 1,
            price: 65000,
            status: "Delivered",
            paymentMethod: "UPI",
            orderDate: "2026-07-01",
        },
        {
            id: 2,
            orderId: "ORD1002",
            customerName: "Priya Verma",
            product: "Wireless Mouse",
            quantity: 2,
            price: 1600,
            status: "Shipped",
            paymentMethod: "Credit Card",
            orderDate: "2026-07-02",
        },
        {
            id: 3,
            orderId: "ORD1003",
            customerName: "Amit Kumar",
            product: "Mechanical Keyboard",
            quantity: 1,
            price: 4500,
            status: "Pending",
            paymentMethod: "Cash on Delivery",
            orderDate: "2026-07-02",
        },
        {
            id: 4,
            orderId: "ORD1004",
            customerName: "Sneha Gupta",
            product: "Monitor",
            quantity: 1,
            price: 18000,
            status: "Processing",
            paymentMethod: "Debit Card",
            orderDate: "2026-07-03",
        },
        {
            id: 5,
            orderId: "ORD1005",
            customerName: "Rohit Singh",
            product: "Headphones",
            quantity: 1,
            price: 3200,
            status: "Delivered",
            paymentMethod: "Net Banking",
            orderDate: "2026-07-03",
        },
        {
            id: 6,
            orderId: "ORD1006",
            customerName: "Neha Kapoor",
            product: "Smart Watch",
            quantity: 1,
            price: 9500,
            status: "Cancelled",
            paymentMethod: "UPI",
            orderDate: "2026-07-04",
        },
        {
            id: 7,
            orderId: "ORD1007",
            customerName: "Vikas Yadav",
            product: "USB Hub",
            quantity: 3,
            price: 2100,
            status: "Delivered",
            paymentMethod: "Credit Card",
            orderDate: "2026-07-05",
        },
        {
            id: 8,
            orderId: "ORD1008",
            customerName: "Anjali Mehta",
            product: "Gaming Chair",
            quantity: 1,
            price: 14500,
            status: "Shipped",
            paymentMethod: "UPI",
            orderDate: "2026-07-05",
        },
        {
            id: 9,
            orderId: "ORD1009",
            customerName: "Karan Malhotra",
            product: "External SSD",
            quantity: 2,
            price: 12000,
            status: "Processing",
            paymentMethod: "Debit Card",
            orderDate: "2026-07-06",
        },
        {
            id: 10,
            orderId: "ORD1010",
            customerName: "Pooja Arora",
            product: "Bluetooth Speaker",
            quantity: 1,
            price: 2800,
            status: "Pending",
            paymentMethod: "Cash on Delivery",
            orderDate: "2026-07-06",
        },
    ];

    res.send({ message: 'Sucessfully send Order Data', data: allorderdataDB })
}